"""Paper-facing tables and the section 59 completion checklist."""

from __future__ import annotations

#: Section 5 requires a three-column table (B0 has / B0 lacks / B1 adds), each row
#: anchored.  Rows B0 already satisfies must NOT be reported as "B1 is stronger".
CAPABILITY_TABLE = [
    ("immutable candidate persistence", "yes", "run_baseline.py:49-51, 67-71",
     "re-expressed with content-addressed identity and UNIQUE(content_hash)", "policies.py candidates DDL"),
    ("complete before/after value audit", "yes", "run_baseline.py:61-65, 139-140",
     "re-expressed with changed_fields, before/after digests and a hash chain", "policies.py audits DDL"),
    ("authorized value", "yes", "run_baseline.py:55-58 approved_values_json",
     "re-expressed with scope_json and policy_version", "policies.py approvals DDL"),
    ("expected / current version", "yes", "run_baseline.py:56", "none", "-"),
    ("compare-and-swap", "yes", "run_baseline.py:133-137 rowcount!=1 -> stale_version", "none", "-"),
    ("atomic transaction + rollback", "yes", "run_baseline.py:108-150 BEGIN IMMEDIATE + ROLLBACK", "none", "-"),
    ("stale-replay rejection", "yes", "run_baseline.py:133-137", "none", "-"),
    ("direct-write exclusion", "yes", "run_baseline.py:67-71 freeze triggers", "none", "-"),
    ("failure injection / rollback", "yes", "run_baseline.py:141-142 fail_after_writes", "none", "-"),
    ("same database backend", "yes", "run_baseline.py:45-46 SQLite", "none", "-"),
    ("canonical JSON equality", "yes", "run_baseline.py:29-30 canonical()", "none", "-"),
    ("reviewer / principal policy", "partial (hard-coded 'reviewer-1')",
     "run_baseline.py:97-98, 104-105",
     "principal registry with role and authorized-field set; FK from approvals",
     "policies.py principals DDL + _principal()"),
    ("evidence persistence", "no", "approvals/candidates have no evidence column (run_baseline.py:49-58)",
     "evidence_hash + evidence_locator persisted on the immutable candidate record",
     "policies.py candidates DDL"),
    ("explicit per-field source map", "no (reconstructable from audit)",
     "run_baseline.py:173-182 reconstruct_sources()",
     "fact_sources table + per-version sources_json + stored==reconstructed check",
     "policies.py fact_sources DDL, _commit_successor()"),
    ("candidate registry richness", "4 columns", "run_baseline.py:49-51",
     "producer, producer_version, selection_artifact_id, expected_fact_version, "
     "evidence_hash, evidence_locator, created_at, content_hash, UNIQUE(content_hash)",
     "policies.py candidates DDL"),
    ("schema versioning / migration marker", "no", "-", "schema_meta table", "policies.py schema_meta DDL"),
    ("explicit approval-consumption guard", "implicit only (changed_domain incidentally refuses replay)",
     "run_baseline.py:127-130", "explicit approval_consumption row inside the transaction",
     "policies.py approval_consumption DDL + submit()"),
    ("admission decision log with reason codes", "no", "-",
     "admission_attempts (records no candidate identity)", "policies.py admission_attempts DDL"),
    ("transaction grouping", "no", "-", "tx_log", "policies.py tx_log DDL"),
    ("tamper-evident audit chain", "no", "-",
     "before/after digests plus prev_row_digest/row_digest chain", "policies.py audits DDL, _commit_successor()"),
    ("post-commit source-map consistency check", "no", "-",
     "stored source map compared with the audit reconstruction (case observation "
     "'stored_matches_reconstruction')", "cases.py two-step-copy-forward observations"),
    ("exact reviewed-candidate binding", "no", "run_baseline.py:193-195 (comment: stores no candidate identity)",
     "still absent in B1 by design (section 7)", "self_audit.json implements_exact_candidate_obligation=false"),
    ("admission-used candidate identity", "no", "-",
     "still absent in B1 by design (section 20)", "self_audit.json section_20_used_candidate_recorded=false"),
    ("distinguish paired equal-valued reviewed candidates", "no",
     "run_baseline.py:458-460 (states identical)",
     "still absent in B1 (identical case outcome reproduced)", "case_results.json B1 paired-reviewed-candidate"),
    ("single-history agreement with candidate-bound", "7 of 8",
     "evidence/r27-standard-practice-baseline/run-2026-09-10/summary.json",
     "7 of 8 reproduced, same two divergences", "normalized/parity.json strengthened_control_B1_vs_Full"),
]

CHECKLIST = [
    ("existing B0 untouched",
     "PASS", "SHA-256 pins verified at run time for run_baseline.py and the E0 demonstrator",
     "manifest.json frozen_artifact_pins"),
    ("existing nine-case control untouched", "PASS",
     "the nine cases are re-driven, not rewritten; the frozen harness is imported",
     "cases.py imports CANDIDATE_BOUND_REFERENCE from the frozen module"),
    ("existing 7/8 result reproducible", "PASS",
     "B0 re-run is byte-identical: summary.json, runs.json and all 10 databases",
     "evidence/reproduction/b0-cf09d099"),
    ("Full candidate-bound implementation untouched", "PASS",
     "the in-process Full is a new realization validated against the frozen reference; "
     "no production module was edited", "normalized/parity.json in_process_full_agreement=9/9"),
    ("new B1 independently versioned", "PASS", "evidence/strong-baseline/{manifest,raw,normalized,paper}",
     "evidence/strong-baseline/manifest.json"),
    ("B1 is stronger than B0 on conventional safeguards", "PASS (with the section 5 discipline)",
     "9 capability rows added; 11 rows that B0 already satisfies are not claimed as increments",
     "paper/table-capability-3col.md"),
    ("B1 approval is still value-bound, not candidate-bound", "PASS",
     "no authority table references candidates; inferred review origin is AMBIGUOUS",
     "normalized/self_audit.json"),
    ("no reviewed-proposal snapshot added to main B1", "PASS",
     "B1's approvals row has reviewed_* columns NULL; the snapshot exists only in the optional B2",
     "raw/2026-09-10/b1_cases/db/*.db"),
    ("no used_candidate_id added to main B1", "PASS",
     "only the optional B2plus variant adds it", "normalized/self_audit.json"),
    ("Full uses decision + authorization binding + exact certificate identity", "PASS",
     "decisions + authorization_bindings, content-addressed certificate ids",
     "policies.py CandidateBoundPolicy"),
    ("E1 has an explicit mapping to the formal identity pair", "PASS",
     "10-row mapping table with exact/approximate classification",
     "normalized/formal_witness_mapping.json"),
    ("concrete candidate identity feasibility checked", "PASS",
     "content-addressed identity over 10 declared fields including created_at; the "
     "DEMO-layer pair q100a/q100b differs only in candidate_id",
     "normalized/candidate_pair_difference_table.json"),
    ("identity scheme not tampered with when identical-content duplicates are impossible", "PASS",
     "the pair is generated through the content-addressed constructor; no uniqueness "
     "constraint was disabled", "cases.py build_registry()"),
    ("source comparison uses reconstruction semantics", "PASS",
     "the frozen B0 reconstruct_sources() is applied to B1's database",
     "cases.py observations_of()"),
    ("ground truth is a test-side oracle only", "PASS",
     "ground_truth_review_target / attempted_admission_candidate appear in the E1 record, "
     "never in a policy database", "strong_baseline/e1.py run()"),
    ("raw database digest used only for stutter/zero-write", "PASS",
     "rejected runs are checked for state_unchanged; semantic claims use the declared projection",
     "cases.py _record(), analysis.project()"),
    ("review-origin inference is a diagnostic, not a production guarantee", "PASS",
     "infer_review_origin() labels Full EXPLICITLY_BOUND and B1/B2 AMBIGUOUS",
     "normalized/self_audit.json"),
    ("new results did not presuppose 7/8", "PASS",
     "B1 reproduces 7/8; B2 and B2plus reach 8/9 and are reported as such",
     "normalized/parity.json"),
    ("unexpected results retained", "PASS",
     "B2/B2plus paired-history distinguishability is retained and drives the section 45 narrowing",
     "reports/Phase7-*.md"),
    ("baseline not weakened to fit the paper's expectation", "PASS",
     "B1 is a strict superset of B0's capabilities; the optional controls exceed it",
     "paper/table-capability-3col.md"),
    ("no over-claiming", "PASS", "report uses the section 49 claim boundary",
     "reports/Phase8-*.md"),
    ("section 7 / 20 field omissions justified by a proved inequality, not by protecting C5", "PASS",
     "E1a proves snapshot(A)==snapshot(B) for equal-valued, same-context, same-evidence "
     "candidates (B2 accepts the substitution); the residual narrowing is reported per section 45",
     "normalized/e1_summary.json B2__evidence_a"),
    ("every Phase 1 conclusion carries an evidence anchor", "PASS",
     "file:line, DDL text or run output for each row",
     "reports/Phase1-*.md, paper/anchors.md"),
    ("section 2 artifact split recorded", "PASS",
     "B0 = run_baseline.py, E0 = value_audit_demo.py, B1 extends B0", "manifest.json b1_extends"),
    ("section 5 three-column table produced and anchored", "PASS", "25 rows", "paper/table-capability-3col.md"),
    ("section 16 DEMO/PROD layering implemented", "PASS",
     "DEMO pair read from the frozen E0 database; PROD analogue constructed through the "
     "content-addressed path and labelled an analogue",
     "normalized/candidate_pair_difference_table.json"),
    ("E1/E2 realistic case uses the recognition path, not the AI-suggestion path", "PASS (design)",
     "the harness models the recognition path (no lineage parent); the AI-suggestion path "
     "is excluded because lineage_parent_ids would be a side channel",
     "reports/Phase7-*.md open items"),
    ("section 16 step 3 filled from the measured difference table", "PASS",
     "'possibly equal' fields are not silently marked equal; the evidence-content question "
     "is reported as UNVERIFIED (O1)", "normalized/candidate_pair_field_visibility.json"),
    ("q100a/q100b physical differences enumerated with a B1-visibility verdict", "PASS",
     "every differing field carries stored_by_B1 and discriminates_histories verdicts",
     "normalized/candidate_pair_field_visibility.json"),
    ("C5 narrowed if the results require it (section 45)", "REQUIRED (see Phase 7)",
     "B2 recovers paired-history distinguishability, so the increment narrows to exact "
     "reviewed-candidate identity when review context is not discriminating",
     "reports/Phase8-paper-patch.md"),
    ("stopped and reclassified if B1 already implements exact binding (section 46)", "N/A",
     "self-audit finds no authority table referencing candidates in B1/B2/B2plus",
     "normalized/self_audit.json"),
]
