"""Regenerate the complete frozen trace grid without modifying measurements."""
import hashlib
import json
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER.parent / 'code/figure-work/evidence/paper-inputs/r21_trace_optimization_summary.json'

def main():
    data = json.loads(SOURCE.read_text(encoding='utf-8'))
    rows = data['results']
    assert len(rows) == data['cells'] == 36
    assert len({(r['fields'], r['versions'], r['records']) for r in rows}) == 36
    assert data['command_failures'] == 0
    assert data['baseline_observations'] == data['current_observations'] == 7200
    lines = [
        '% Generated by scripts/build_trace_grid.py; source SHA-256: ' + hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        r'\begingroup\small',
        r'\begin{longtable}{@{}rrrrrrr@{}}',
        r'\caption{Complete frozen reverse-trace grid (latencies in milliseconds).}\label{tab:trace-complete-grid}\\',
        r'\toprule Fields & Versions & Records & Base p50 & Opt. p50 & Base p95 & Opt. p95 \\',
        r'\midrule\endfirsthead',
        r'\toprule Fields & Versions & Records & Base p50 & Opt. p50 & Base p95 & Opt. p95 \\',
        r'\midrule\endhead',
        r'\bottomrule\endfoot',
    ]
    for r in sorted(rows, key=lambda r: (r['fields'], r['versions'], r['records'])):
        assert r['baseline_trials'] == r['current_trials'] == 200
        assert r['current_sql_statements'] == [12, 12]
        values = [str(r[k]) for k in ('fields', 'versions', 'records')]
        values += [format(r[k], '.3f') for k in ('baseline_p50_ms', 'current_p50_ms', 'baseline_p95_ms', 'current_p95_ms')]
        lines.append(' & '.join(values) + r' \\')
    lines += [r'\end{longtable}', r'\endgroup', '']
    target = PAPER / 'tables/generated/trace_complete_grid.tex'
    target.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    print('Verified and generated all 36 cells:', target)

if __name__ == '__main__':
    main()
