"""Generate the repeated-benchmark runtime-failure table from the frozen Final input.

The script reads only the manifest-bound statistical_analysis.json staged in
``evidence/agent-authority-benchmark-v2/manuscript-input/2026-09-03-three-config-10x/``
and recomputes the runtime terminal-class breakdown.  It refuses to run when
the breakdown does not sum to the locked runtime-failure totals, and it embeds
the source SHA-256 in the generated file so drift is detectable.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from typing import Any

FAILURE_TERMINAL_CLASSES = (
    "MODEL_API_FAILURE",
    "INVALID_OUTPUT",
    "HARNESS_FAILURE",
    "TIMEOUT",
    "SETUP_FAILURE",
    "TOOL_RUNTIME_FAILURE",
)

CONFIGURATIONS = ("D1", "G1", "G2")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _terminal_counts(classes: dict[str, Any]) -> dict[str, int]:
    return {name: int(classes.get(name, 0)) for name in FAILURE_TERMINAL_CLASSES}


def _escape(value: str) -> str:
    return value.replace("_", "\\_")


def build_table(input_path: Path) -> str:
    data = _load_and_validate(input_path)

    pooled = _terminal_counts(data["primary"]["terminal_classes"])
    rows: list[str] = []
    for name in FAILURE_TERMINAL_CLASSES:
        total = pooled[name]
        if total == 0:
            continue
        cells = [
            str(_terminal_counts(
                data["primary"]["per_configuration"][config]["terminal_classes"]
            )[name])
            for config in CONFIGURATIONS
        ]
        rows.append(
            f"{_escape(name)} & {total} & " + " & ".join(cells) + " \\\\"
        )

    runtime = int(data["primary"]["runtime_failures"])
    config_totals = [
        int(data["primary"]["per_configuration"][config]["runtime_failures"])
        for config in CONFIGURATIONS
    ]

    source_sha256 = _sha256(input_path)
    header = (
        "% Generated by scripts/build_runtime_failure_table.py from the frozen Final\n"
        "% statistical_analysis.json staged in the manuscript-input bundle.\n"
        f"% source_sha256: {source_sha256}\n"
    )
    return (
        header
        + "\\begin{table*}[t]\n"
        + "\\centering\n"
        + "\\footnotesize\n"
        + "\\caption{Runtime-failure terminal classes in the repeated benchmark.}\n"
        + "\\label{tab:runtime-failure}\n"
        + "\\begin{tabularx}{\\textwidth}{@{}l*{4}{>{\\centering\\arraybackslash}X}@{}}\n"
        + "\\toprule\n"
        + "Terminal class & Total & D1 & G1 & G2 \\\\\n"
        + "\\midrule\n"
        + "\n".join(rows)
        + "\n"
        + "\\midrule\n"
        + f"Total & {runtime} & "
        + " & ".join(str(value) for value in config_totals)
        + " \\\\\n"
        + "\\bottomrule\n"
        + "\\end{tabularx}\n"
        + "\\end{table*}\n"
    )


def _load_and_validate(input_path: Path) -> dict[str, Any]:
    input_path = input_path.resolve()
    if not input_path.is_file():
        raise ValueError(f"statistical_analysis.json not found: {input_path}")

    data = __import__("json").loads(input_path.read_text(encoding="utf-8"))
    primary = data.get("primary")
    if not isinstance(primary, dict):
        raise ValueError("statistical_analysis.json has no primary block")

    pooled = _terminal_counts(primary["terminal_classes"])
    runtime = int(primary["runtime_failures"])
    if sum(pooled.values()) != runtime:
        raise ValueError(
            "runtime terminal-class sum does not equal primary.runtime_failures: "
            f"{sum(pooled.values())} != {runtime}"
        )

    for config in CONFIGURATIONS:
        per = primary["per_configuration"][config]
        counts = _terminal_counts(per["terminal_classes"])
        expected = int(per["runtime_failures"])
        if sum(counts.values()) != expected:
            raise ValueError(
                f"{config} runtime terminal-class sum does not equal its "
                f"runtime_failures: {sum(counts.values())} != {expected}"
            )

    if int(primary["planned_executions"]) != 1260:
        raise ValueError("planned_executions is not the locked 1,260")
    return data


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    rendered = build_table(Path(args.input))
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"wrote {output.resolve()} ({len(rendered)} bytes)")


if __name__ == "__main__":
    main()
