"""Build the runtime-terminal by endpoint-evaluability cross-table."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


FAILURES = ("MODEL_API_FAILURE", "INVALID_OUTPUT", "HARNESS_FAILURE", "TIMEOUT")
CONFIGS = ("D1", "G1", "G2")


def analyze(path: Path) -> dict[str, object]:
    rows = json.loads(path.read_text(encoding="utf-8"))
    if len(rows) != 1260:
        raise ValueError(f"expected 1,260 frozen rows, found {len(rows)}")
    selected = [row for row in rows if row.get("terminal_class") in FAILURES]
    if len(selected) != 93:
        raise ValueError(f"expected 93 runtime failures, found {len(selected)}")
    classes: dict[str, dict[str, int]] = {}
    for terminal in FAILURES:
        group = [row for row in selected if row["terminal_class"] == terminal]
        classes[terminal] = {
            "total": len(group),
            **{config: sum(row["model_config_id"] == config for row in group) for config in CONFIGS},
            "authority_evaluable": sum(row.get("authority_evaluable") is True for row in group),
            "behavior_evaluable": sum(row.get("agent_behavior_evaluable") is True for row in group),
        }
    return {
        "classes": classes,
        "total": len(selected),
        "authority_evaluable": sum(row.get("authority_evaluable") is True for row in selected),
        "behavior_evaluable": sum(row.get("agent_behavior_evaluable") is True for row in selected),
        "behavior_false": sum(
            row.get("agent_behavior_evaluable") is True and row.get("agent_task_completed") is False
            for row in selected
        ),
    }


def build_table(path: Path) -> str:
    result = analyze(path)
    rows = []
    for terminal in FAILURES:
        item = result["classes"][terminal]
        name = terminal.replace("_", "\\_")
        rows.append(
            f"{name} & {item['total']} & {item['D1']} & {item['G1']} & {item['G2']} & "
            f"{item['authority_evaluable']} & {item['behavior_evaluable']} \\\\"
        )
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return (
        "% Generated by paper/scripts/build_runtime_endpoint_table.py.\n"
        f"% source_sha256: {digest}\n"
        "\\begin{table}[t]\n\\centering\n\\footnotesize\n"
        "\\caption{Runtime-failure terminal classes crossed with endpoint evaluability.}\n"
        "\\label{tab:runtime-endpoint}\n"
        "\\begin{tabular}{@{}lrrrrrr@{}}\n"
        "\\toprule\nTerminal class & Total & D1 & G1 & G2 & "
        "\\shortstack{Authority-\\\\evaluable} & \\shortstack{Behavior-\\\\evaluable} \\\\\n"
        "\\midrule\n"
        + "\n".join(rows)
        + "\n\\midrule\n"
        + f"Total & {result['total']} & 76 & 4 & 13 & {result['authority_evaluable']} & "
        + f"{result['behavior_evaluable']} \\\\\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    rendered = build_table(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
