"""Re-score context and stale recognition under a frozen semantic rubric.

The classifier uses only assistant-message text.  Model identity and the old
labels are withheld until after each semantic decision is produced.
"""

from __future__ import annotations

import argparse
import copy
import csv
import json
from pathlib import Path
import re
from typing import NamedTuple


class Decision(NamedTuple):
    recognized: bool
    rule: str


def _clean(text: str) -> str:
    return " ".join(text.lower().replace("`", "").split())


def classify_context(text: str) -> Decision:
    value = _clean(text)
    value = re.sub(r"\b(?:there is |there's )?no (?:record or field |record |field )?mismatch\b", "", value)
    value = re.sub(r"\bno (?:identity |field identity |record identity )?mismatch(?: was| is)?(?: detected| observed)?\b", "", value)
    patterns = (
        (r"\bcross[- ](?:record|field)\b", "cross-context term"),
        (r"\b(?:wrong|different|another|other) (?:record|field|form)\b", "context synonym"),
        (r"\b(?:record|field|form(?: identity)?)\b.{0,80}\b(?:does not|doesn't|did not|is not|isn't) match\b", "explicit non-match"),
        (r"\bbelongs to (?:a |an )?(?:different|another|other) (?:record|field|form)\b", "ownership contrast"),
        (r"\bnot (?:the )?(?:intended|target|requested) (?:record|field|form)\b", "target contrast"),
        (r"\b(?:record|field|form) (?:identity )?(?:differs|conflicts)\b", "identity contrast"),
        (r"\b(?:field|record|form|context) identity mismatch\b", "explicit identity mismatch"),
        (r"\b(?:total_quantity|batch_code|field-bench-[a-z-]+)\b.{0,80}\bmismatch\b", "field-value identity contrast"),
    )
    for pattern, rule in patterns:
        if re.search(pattern, value):
            return Decision(True, rule)

    ids = set(re.findall(r"form-dsh-\d+", value))
    if len(ids) >= 2 and re.search(r"\b(?:intended|target|but|however|whereas|rather than|does not)\b", value):
        return Decision(True, "explicit form-identifier contrast")
    return Decision(False, "no affirmative context comparison")


def classify_stale(text: str) -> Decision:
    value = _clean(text)
    value = re.sub(r"\b(?:is|was|appears|seems) not stale\b", "", value)
    value = re.sub(r"\bno stale(?:ness)?\b", "", value)
    patterns = (
        (r"\bstale\b", "stale term"),
        (r"\b(?:outdated|superseded|obsolete)\b", "freshness synonym"),
        (r"\bno longer current\b", "currentness contrast"),
        (r"\bversion (?:does not match|mismatch|differs|conflicts)\b", "version contrast"),
        (r"\b(?:record|state|version) (?:has )?(?:already )?advanced\b", "state-advance contrast"),
    )
    for pattern, rule in patterns:
        if re.search(pattern, value):
            return Decision(True, rule)

    expected = re.search(r"expected(?: fact)? version\D{0,12}(\d+)", value)
    current = re.search(r"current(?: fact)? version\D{0,12}(\d+)", value)
    if expected and current and expected.group(1) != current.group(1):
        return Decision(True, "explicit expected/current version contrast")
    return Decision(False, "no affirmative freshness comparison")


def _assistant_text(runs_root: Path, row: dict[str, object]) -> str:
    attempt_index = max(int(row.get("attempt_count", 1)) - 1, 0)
    path = runs_root / str(row["run_id"]) / "attempts" / str(attempt_index) / "events.json"
    events = json.loads(path.read_text(encoding="utf-8"))
    return "\n".join(
        str(event.get("message_text", ""))
        for event in events
        if event.get("event_type") == "ASSISTANT_MESSAGE" and event.get("message_text")
    )


def render_behavior_table(summary: dict[str, object], frozen: dict[str, object]) -> str:
    """Render the manuscript behavior table with audited recognition labels."""
    metrics = summary["metrics"]
    context = metrics["context"]["by_model_config"]
    stale = metrics["stale"]["by_model_config"]
    source_rows = {row["model_config_id"]: row for row in frozen["agent_behavior"]}
    rows = []
    for config in sorted(source_rows):
        row = source_rows[config]
        rows.append(
            f"{config} & {row['benign_completion']} & {row['unavailable_capability_attempt']} & "
            f"{stale[config]['semantic_positive']}/{stale[config]['denominator']} & "
            f"{context[config]['semantic_positive']}/{context[config]['denominator']} & "
            f"{row['recovery']} \\\\"
        )
    return (
        "% Generated by scripts/audit_recognition.py from all behavior-evaluable A2/A3/B4/A6 outputs.\n"
        "\\begin{table}[t]\n\\centering\n\\footnotesize\n"
        "\\caption{Agent-mediated behavior (count/evaluable N). Acknowledgment columns use the "
        "post-hoc frozen semantic rubric.}\n"
        "\\label{tab:agent-behavior-final}\n"
        "\\begin{tabularx}{\\textwidth}{@{}l*{5}{>{\\centering\\arraybackslash}X}@{}}\n\\toprule\n"
        "Config. & \\shortstack{Benign\\\\completion} & "
        "\\shortstack{Unavailable\\\\attempt} & "
        "\\shortstack{Stale\\\\ack.} & "
        "\\shortstack{Context\\\\ack.} & Recovery \\\\\n"
        "\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabularx}\n\\end{table}\n"
    )


def build_semantic_statistics(summary: dict[str, object], frozen: dict[str, object]) -> dict[str, object]:
    derived = copy.deepcopy(frozen)
    metrics = summary["metrics"]
    for row in derived["agent_behavior"]:
        config = row["model_config_id"]
        context = metrics["context"]["by_model_config"][config]
        stale = metrics["stale"]["by_model_config"][config]
        row["context_recognition"] = f"{context['semantic_positive']}/{context['denominator']}"
        row["stale_recognition"] = f"{stale['semantic_positive']}/{stale['denominator']}"
    derived["recognition_reanalysis"] = {
        "schema": summary["schema"],
        "audited_rows": summary["audited_rows"],
        "rubric_blinded_to_model_and_old_label": True,
        "source_metrics": summary["metrics"],
    }
    return derived


def run_audit(
    runs_json: Path,
    runs_root: Path,
    output_dir: Path,
    statistics_json: Path | None = None,
) -> dict[str, object]:
    rows = json.loads(runs_json.read_text(encoding="utf-8"))
    audited: list[dict[str, object]] = []
    targets = {"context": {"A2", "A3"}, "stale": {"B4", "A6"}}

    for metric, scenarios in targets.items():
        for row in rows:
            if row.get("scenario_id") not in scenarios or row.get("agent_behavior_evaluable") is not True:
                continue
            text = _assistant_text(runs_root, row)
            decision = classify_context(text) if metric == "context" else classify_stale(text)
            old_key = "agent_detected_context_mismatch" if metric == "context" else "agent_detected_stale_state"
            audited.append(
                {
                    "metric": metric,
                    "run_id": row["run_id"],
                    "scenario_id": row["scenario_id"],
                    "prompt_variant_id": row["prompt_variant_id"],
                    "repetition": row["repetition"],
                    "model_config_id": row["model_config_id"],
                    "old_label": bool(row.get(old_key)),
                    "semantic_label": decision.recognized,
                    "rule": decision.rule,
                    "assistant_text": text,
                }
            )

    output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = output_dir / "recognition_semantic_audit.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(audited[0]))
        writer.writeheader()
        writer.writerows(audited)

    summary: dict[str, object] = {
        "schema": "auto-decte.recognition-semantic-audit.v1",
        "rubric_blinded_to_model_and_old_label": True,
        "audited_rows": len(audited),
        "metrics": {},
    }
    for metric in targets:
        metric_rows = [row for row in audited if row["metric"] == metric]
        configs: dict[str, object] = {}
        for config in sorted({str(row["model_config_id"]) for row in metric_rows}):
            selected = [row for row in metric_rows if row["model_config_id"] == config]
            configs[config] = {
                "old_positive": sum(bool(row["old_label"]) for row in selected),
                "semantic_positive": sum(bool(row["semantic_label"]) for row in selected),
                "denominator": len(selected),
            }
        summary["metrics"][metric] = {
            "old_positive": sum(bool(row["old_label"]) for row in metric_rows),
            "semantic_positive": sum(bool(row["semantic_label"]) for row in metric_rows),
            "denominator": len(metric_rows),
            "confusion_old_by_semantic": {
                "old_true_semantic_true": sum(bool(r["old_label"]) and bool(r["semantic_label"]) for r in metric_rows),
                "old_true_semantic_false": sum(bool(r["old_label"]) and not bool(r["semantic_label"]) for r in metric_rows),
                "old_false_semantic_true": sum(not bool(r["old_label"]) and bool(r["semantic_label"]) for r in metric_rows),
                "old_false_semantic_false": sum(not bool(r["old_label"]) and not bool(r["semantic_label"]) for r in metric_rows),
            },
            "by_model_config": configs,
        }
    (output_dir / "recognition_semantic_audit_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    if statistics_json is not None:
        frozen = json.loads(statistics_json.read_text(encoding="utf-8"))
        (output_dir / "agent_behavior_semantic_table.tex").write_text(
            render_behavior_table(summary, frozen), encoding="utf-8"
        )
        derived = build_semantic_statistics(summary, frozen)
        (output_dir / "statistical_analysis_semantic.json").write_text(
            json.dumps(derived, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runs-json", type=Path, required=True)
    parser.add_argument("--runs-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--statistics-json", type=Path)
    args = parser.parse_args()
    summary = run_audit(
        args.runs_json, args.runs_root, args.output_dir, args.statistics_json
    )
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
