module auto_decte_batch_s2

open auto_decte_batch

// S2 repeats the complete canonical command catalog at larger bounds.

check StateInvariantPreserved for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P0NoMachineAuthoritativeWrite for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P1ExactContext for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P3AuthorizationIntegrity for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P4Freshness for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P5TransitionBijection for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check FullNoPartialItemEffects for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check RejectionHasNoEffect for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check SingletonContractEquivalence for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check SingletonEffectEquivalence for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check FullRejectsAblatedAttempt for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P6MissingAnchorIncomplete for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check P6DuplicateSourceVersionIncomplete for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
check LegalAdmissionTraceCompleteUnderWellFormedPre for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator

run SAT_BATCH_accept_multi { some e : BatchAdmissionEvent | batchAcceptMulti[e] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_BATCH_correction_multi { some e : BatchAdmissionEvent | batchCorrectionMulti[e] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 8 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_BATCH_mixed_accept_correction { some e : BatchAdmissionEvent | batchMixed[e] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 8 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_BATCH_same_value_multi { some e : BatchAdmissionEvent | batchSameValueMulti[e] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_BATCH_initial_snapshot { some e : BatchAdmissionEvent | batchInitialSnapshot[e] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_BATCH_singleton { some e : BatchAdmissionEvent | singletonLegal[e] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 3 EvidenceContent, 4 EvidenceLocator

run SAT_ABL_1_effective_pair { pairedAblationWitness[ABL_1] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_2a_effective_pair { pairedAblationWitness[ABL_2a] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_2b_effective_pair { pairedAblationWitness[ABL_2b] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_3_effective_pair { pairedAblationWitness[ABL_3] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_4a_effective_pair { pairedAblationWitness[ABL_4a] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_4b_effective_pair { pairedAblationWitness[ABL_4b] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_5_effective_pair { pairedAblationWitness[ABL_5] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_6_effective_pair { pairedAblationWitness[ABL_6] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 9 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_8_effective_pair { pairedAblationWitness[ABL_8] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_9_effective_pair { pairedAblationWitness[ABL_9] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator
run SAT_ABL_10_effective_pair { pairedAblationWitness[ABL_10] } for 3 Record, 4 Field, 8 Version, 8 Candidate, 8 Certificate, 8 Authorization, 8 Evidence, 8 Value, 4 Producer, 4 Principal, 8 CertId, 5 State, 5 Event, 8 AdmissionItem, 8 Transition, 4 EvidenceContent, 4 EvidenceLocator

run SAT_P6_legal_anchor_loss { some a : BatchAdmissionEvent, t : TamperEvent | anchorLossWitness[a, t] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 7 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 7 AdmissionItem, 9 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_P6_legal_anchor_replacement { some a : BatchAdmissionEvent, t : TamperEvent | anchorReplacementWitness[a, t] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 8 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 7 AdmissionItem, 10 Transition, 3 EvidenceContent, 4 EvidenceLocator
run SAT_P6_legal_source_version_duplicate { some a : BatchAdmissionEvent, t : TamperEvent | sourceDuplicateWitness[a, t] } for 3 Record, 4 Field, 8 Version, 7 Candidate, 7 Certificate, 7 Authorization, 7 Evidence, 8 Value, 4 Producer, 4 Principal, 7 CertId, 5 State, 5 Event, 7 AdmissionItem, 10 Transition, 3 EvidenceContent, 4 EvidenceLocator
